[flavor]
dark = "catppuccin-mocha"

[app]
overall = { bg = "#1e1e2e" }

[mode]

normal_main = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
normal_alt  = { fg = "#89b4fa", bg = "#1e1e2e"}

# Select mode
select_main = { fg = "#1e1e2e", bg = "#94e2d5", bold = true }
select_alt  = { fg = "#94e2d5", bg = "#313244" }

# Unset mode
unset_main = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }
unset_alt  = { fg = "#f2cdcd", bg = "#313244" }

[filetype]
rules = [
	# Image
	{ mime = "image/*", fg = "#94e2d5" },
	# Media
	{ mime = "{audio,video}/*", fg = "#f9e2af" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#9399b2" },
	# Office Documents
    { mime = "application/openxmlformats-officedocument.*", fg = "#a6e3a1" },
    { mime = "application/oasis.opendocument.*", fg = "#a6e3a1" },
    { mime = "application/ms-*", fg = "#a6e3a1" },
    { mime = "application/msword", fg = "#a6e3a1" },
    { name = "*.docx", fg = "#a6e3a1" },

	{ url = "*", is = "orphan", fg = "#f38ba8" },
	{ url = "*/", is = "orphan", fg = "#f38ba8" },
	{ url = "*", is = "link", fg = "#94e2d5" },
	{ url = "*/", is = "link", fg = "#94e2d5" },
	# Fallback
	{ url = "*", fg = "#bac2de" },
	{ url = "*/", fg = "#89b4fa" },
]

[icon]
dirs = [
	{ name = ".config", text = "", fg = "#fab387" },
	{ name = ".git", text = "", fg = "#89b4fa" },
	{ name = ".github", text = "", fg = "#89b4fa" },
	{ name = ".npm", text = "", fg = "#89b4fa" },
	{ name = "Projects", text = "󰲋", fg = "#89b4fa" },
	{ name = "projects", text = "󰲋", fg = "#89b4fa" },
	{ name = "Desktop", text = "", fg = "#89b4fa" },
	{ name = "Development", text = "", fg = "#89b4fa" },
	{ name = "Documents", text = "", fg = "#89b4fa" },
	{ name = "Downloads", text = "", fg = "#89b4fa" },
	{ name = "Library", text = "", fg = "#89b4fa" },
	{ name = "Movies", text = "", fg = "#89b4fa" },
	{ name = "Music", text = "", fg = "#89b4fa" },
	{ name = "Pictures", text = "", fg = "#89b4fa" },
	{ name = "Public", text = "", fg = "#89b4fa" },
	{ name = "Videos", text = "", fg = "#89b4fa" },
]
conds = [
	# Special files
	{ if = "orphan", text = "󰌺", fg = "#f38ba8" },
	{ if = "link", text = "", fg = "#94e2d5" },
	{ if = "block", text = "", fg = "#f2cdcd" },
	{ if = "char", text = "", fg = "#f2cdcd" },
	{ if = "fifo", text = "", fg = "#f2cdcd" },
	{ if = "sock", text = "", fg = "#f2cdcd" },
	{ if = "sticky", text = "", fg = "#f2cdcd" },
	{ if = "dummy", text = "", fg = "#f38ba8" },

	# Fallback
	{ if = "dir", text = "", fg = "#89b4fa" },
	{ if = "exec", text = "", fg = "#a6e3a1" },
	{ if = "!dir", text = "", fg = "#bac2de" },
]
